name: benta_lacos
description: "Projeto Flutter - Benta Laços"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Versões compatíveis para o Editor de Texto
  flutter_quill: ^11.5.0
  intl: 0.20.2 # Mantenha APENAS esta versão

  # FIREBASE
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0

  # PDF / RELATÓRIOS (Removi o intl duplicado daqui)
  pdf: ^3.11.3
  printing: ^5.13.1
  fl_chart: ^0.66.0

  # RESTANTE DAS DEPENDÊNCIAS
  provider: ^6.1.2
  url_launcher: ^6.3.0
  flutter_slidable: ^3.0.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  flutter_card_swiper: ^7.0.1
  confetti: ^0.7.0
  qr_flutter: ^4.1.0
  mask_text_input_formatter: ^2.5.0
  file_picker: ^8.0.0
  http: ^1.2.1
  brasil_fields: ^1.15.0
  validatorless: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    # Logos e banners
    - assets/imagens/logo.png
    - assets/imagens/banner_principal.png

    # Pastas gerais
    - assets/imagens/carousel/
    - assets/imagens/icons/
    - assets/imagens/payments/
    - assets/imagens/social/
    - assets/imagens/tela_fundo/
    - assets/imagens/clientes/

    # Produtos
    - assets/imagens/produtos/tiaras/
    - assets/imagens/produtos/lacos/

    # Ícones personalizados
    - assets/imagens/icones_personalizados/laco.png
    - assets/imagens/icones_personalizados/tiara.png
    - assets/imagens/icones_personalizados/presilha.png
    - assets/imagens/icones_personalizados/kit.png
    - assets/imagens/icones_personalizados/faixa.png
